const rankings= [
    { id: 1, title: 'Martyr!', author: 'Kaveh Akbar', genre: 'Fiction', weeks: 1},
    { id: 2, title: 'James', author: 'Percival Everett', genre: 'Fiction', weeks: 2},
    { id: 3, title: 'The Life Impossible', author: 'Matt Haig', genre: 'Fiction', weeks: 3},
    { id: 4, title: 'After Annie', author: 'Anna Quindlen', genre: 'Fiction', weeks: 2},
    { id: 5, title: 'The God of the Woods', author: 'Liz Moore', genre: 'Fiction', weeks: 5 },
    { id: 6, title: 'Intermezzo', author: 'Sally Rooney', genre: 'Fiction', weeks: 4},
    { id: 7, title: 'The Housemaid', author: 'Freida McFadden', genre: 'Mystery', weeks: 15},
    { id: 8, title: 'The Hunter', author: 'Tana French', genre: 'Mystery', weeks: 8},
    { id: 9, title: 'The Blue Hour', author: 'Paula Hawkins', genre: 'Mystery', weeks: 6},
    { id: 10, title: 'We Solve Murders', author: 'Richard Osman', genre: 'Mystery', weeks: 9},
    { id: 11, title: 'The Grey Wolf', author: 'Louis Penny', genre: 'Mystery', weeks: 10},
    { id: 12, title: 'The Last One at the Wedding', author: 'Jason Rekulak', genre: 'Mystery', weeks: 4},
    { id: 13, title: "Merlin's Tour of the Universe", author: 'Neil DeGrasse Tyson', genre: 'Nonfiction', weeks: 6},
    { id: 14, title: 'John Lewis - A Life', author: 'David Greenberg', genre: 'Nonfiction', weeks: 15},
    { id: 15, title: 'Nexus', author: 'Yuval Noah Harari', genre: 'Nonfiction', weeks: 8},
    { id: 16, title: "Don't Believe Everything You Think", author: 'Joseph Nguyen', genre: 'Nonfiction', weeks: 5},
    { id: 17, title: 'The Elements of Marie Curie', author: 'Dava Sobel', genre: 'Nonfiction', weeks: 8},
    { id: 18, title: 'The Backyard Bird Chronicles', author: 'Amy Tan', genre: 'Nonfiction', weeks: 8},
    { id: 19, title: 'The Most Wonderful Crime of the Year', author: 'Ally Carter', genre: 'Romance', weeks: 4},
    { id: 20, title: 'This Summer Will Be Different', author: 'Carley Fortune', genre: 'Romance', weeks: 4},
    { id: 21, title: 'Not In Love', author: 'Ali Hazelwood', genre: 'Romance', weeks: 6},
    { id: 22, title: 'Funny Story', author: 'Emily Henry', genre: 'Romance', weeks: 15},
    { id: 23, title: 'The Paradise Problem', author: 'Christina Lauren', genre: 'Romance', weeks: 10},
    { id: 24, title: 'A Jingle Bell Mingle', author: 'Julie Murphy & Sierra Simone', genre: 'Romance', weeks: 5},
]  